[application]

[bundle]
icon = ["icons/icon.png"]

[android]
package = "com.geoconnect.app"
version_name = "0.1.0"
version_code = 1

[web.app]

# HTML title tag content
title = "geoconnect"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
